### ISSUE TITLE
which files should be included under /path/to/corpus

### ISSUE THREAD

**Issue by crystina-z** [smt-HS/DeepTileBars-release#1]
Hi I'm trying to run the model following the flow, yet when it comes to 'extract and cleaning document', no new file was generated. I went through the code and it seems assuming docs under `/path/to/corpus` should have tags like `<DOC>`, `<DOCNO>` etc. However I failed to find such files in either ./data, ./qrel or ./MQ2008 folder. 

The query file and ./MQ2008 folder are downloaded from provided links. thanks!

**Comment by smt-HS** [comment]
Hi, 

Sorry for the ambiguity in the documentation. 

MQ2008 only contains pre-built features. It does not contain the original text, which is required by DeepTileBars. 
  
`/path/to/corpus` is the path to the original corpus, i.e. the [Gov2](http://ir.dcs.gla.ac.uk/test_collections/access_to_data.html) collection, based on which MQ2008 is built.

**Comment by crystina-z** [comment]
got it and thanks for the link!
